# Site settings
title:       Leavez
email:       info@leavez.xyz
author:      Leavez
description: "Leavez's blog"
baseurl:     ""
url:         "https://leavez.xyz"
timezone:    Asia/Beijing

# Google analytics
google_analytics: "UA-74152229-1"

# Optional features
animated:           false
mainPageAnimated:   false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
# disqus_shortname:

# Social icons
show_social_icons: false
github_username:
dribbble_username:
stackoverflow_id:
twitter_username:
linkedin_username:
weibo_id:
instagram_username:
behance_id:


# Build settings
# markdown: kramdown
kramdown:
  input: GFM
permalink:    pretty
paginate:     3
paginate_path: "/page:num/"
sass:
  compressed: true
gems :
  - jekyll-paginate
  - jekyll-sitemap
  
plugins:
  - jekyll-sitemap
